force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>Objeto de livros</description>
    <label>Livro</label>
    <nameField>
        <label>Titulo do Livro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz__c/Quiz__c.object-meta.xml
<CustomObject>
    <label>Questionario</label>
    <nameField>
        <displayFormat>Q-{0}</displayFormat>
        <label>Numero do Quiz</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questionarios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quiz__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <label>Livro</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Questionarios</relationshipLabel>
    <relationshipName>Quizzes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Reading__c/Reading__c.object-meta.xml
<CustomObject>
    <label>Leitura</label>
    <nameField>
        <displayFormat>L-{0}</displayFormat>
        <label>Numero da Leitura</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leituras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reading__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Estante de livros</relationshipLabel>
    <relationshipName>Bookshelf</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reading__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Livro</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Leituras</relationshipLabel>
    <relationshipName>Bookshelf</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reading__c/fields/Quiz__c.field-meta.xml
<CustomField>
    <fullName>Quiz__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Questionario</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Book__c</field>
            <operation>equals</operation>
            <valueField>Quiz__c.Book__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quiz__c</referenceTo>
    <relationshipLabel>Leituras</relationshipLabel>
    <relationshipName>Readings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IntegrationReadings.cls
@RestResource(urlMapping='/readings/*')
global with sharing class IntegrationReadings {

    @HttpGet
    global static List<Reading__c> getReadings() {
        RestRequest req = RestContext.request;
        Map<String,String> parameters = req.params;

        List<Reading__c> readList = new List<Reading__c>();

        RestResponse res = RestContext.response;
        res.statusCode = 200;        

        String username = parameters.get('username');

        if(String.isEmpty(username)) {
            res.statusCode = 414;
            return readList;
        }

        String fields = String.join(IntegrationUtils.getFields('Reading__c'), ', ');

        String fieldsBook = String.join(
        IntegrationUtils.addRelationshipObjectToFields(IntegrationUtils.getFields('Book__c'), 'Book__r'), 
            ','
        );

        String fieldsQuiz = String.join(
        IntegrationUtils.addRelationshipObjectToFields(IntegrationUtils.getFields('Quiz__c'), 'Quiz__r'), 
            ','
        );

        String query = 'SELECT ' + fields + ', ' + fieldsBook + ', ' + fieldsQuiz +
                        ' FROM Reading__c WHERE Account__r.Username__c =: username ORDER BY LastModifiedDate DESC';

        readList = Database.query(query);
        return readList;
    }
}