force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>Objeto de livros</description>
    <label>Livro</label>
    <nameField>
        <label>Titulo do Livro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/ISBN10__c.field-meta.xml
<CustomField>
    <fullName>ISBN10__c</fullName>
    <externalId>true</externalId>
    <label>ISBN10</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Book__c/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <externalId>true</externalId>
    <label>ISBN</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BookCategory__c/BookCategory__c.object-meta.xml
<CustomObject>
    <label>Categoria do livro</label>
    <nameField>
        <displayFormat>C-{0}</displayFormat>
        <label>Numero da Categoria do livro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Categorias dos livros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BookCategory__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Livro</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Categorias do livro</relationshipLabel>
    <relationshipName>BookCategories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BookCategory__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Categoria</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Livros da Categoria</relationshipLabel>
    <relationshipName>BookCategories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>Categoria dos livros</description>
    <label>Categoria</label>
    <nameField>
        <label>Nome da Categoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ID da Categoria</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BookCategoryHelper.cls
public with sharing class BookCategoryHelper {
    
    public static void setExternalId(List<BookCategory__c> newRecordList) {
        Set<Id> bookIdsSet = new Set<Id>();
        Set<Id> categoryIdsSet = new Set<Id>();

        for(BookCategory__c bookCategory : newRecordList) {
            bookIdsSet.add(bookCategory.Book__c);
            categoryIdsSet.add(bookCategory.Category__c);
        }

        Map<Id, Book__c> bookMap = new Map<Id, Book__c>([SELECT Id, ISBN__c, ISBN10__c FROM Book__c WHERE Id IN: bookIdsSet]);
        Map<Id, Product2> categoryMap = new Map<Id, Product2>([SELECT Id, ExternalId__c FROM Product2 WHERE Id IN: categoryIdsSet]);

        for(BookCategory__c bookCategory : newRecordList) {
            String isbn10 = bookMap.get(bookCategory.Book__c).ISBN10__c;
            String isbn13 = bookMap.get(bookCategory.Book__c).ISBN__c;
            String externalId = categoryMap.get(bookCategory.Category__c).ExternalId__c;

            if(!String.isEmpty(isbn10)) {
                bookCategory.ExternalId10__c = isbn10.trim() + externalId.trim();
            }

            if(!String.isEmpty(isbn13)) {
                bookCategory.ExternalId13__c = isbn13.trim() + externalId.trim();
            }
        }
    }
}