force-app/main/default/objects/Book__c/Book__c.object-meta.xml
<CustomObject>
    <description>Objeto de livros</description>
    <label>Livro</label>
    <nameField>
        <label>Titulo do Livro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Livros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c/fields/ISBN10__c.field-meta.xml
<CustomField>
    <fullName>ISBN10__c</fullName>
    <externalId>true</externalId>
    <label>ISBN10</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Book__c/fields/ISBN__c.field-meta.xml
<CustomField>
    <fullName>ISBN__c</fullName>
    <externalId>true</externalId>
    <label>ISBN</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BookCategory__c/BookCategory__c.object-meta.xml
<CustomObject>
    <label>Categoria do livro</label>
    <nameField>
        <displayFormat>C-{0}</displayFormat>
        <label>Numero da Categoria do livro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Categorias dos livros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BookCategory__c/fields/Book__c.field-meta.xml
<CustomField>
    <fullName>Book__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Livro</label>
    <referenceTo>Book__c</referenceTo>
    <relationshipLabel>Categorias do livro</relationshipLabel>
    <relationshipName>BookCategories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BookCategory__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Categoria</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Livros da Categoria</relationshipLabel>
    <relationshipName>BookCategories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>Categoria dos livros</description>
    <label>Categoria</label>
    <nameField>
        <label>Nome da Categoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IntegrationBooks.cls
@RestResource(urlMapping='/books/*')
global with sharing class IntegrationBooks {
    
    @HttpGet
    global static List<Book__c> getBooks() {
        RestRequest req = RestContext.request;
        Map<String,String> parameters = req.params;

        String title = parameters.get('book_name');
        String isbn13 = parameters.get('isbn_13');
        String isbn10 = parameters.get('isbn_10');

        String fieldsBook = String.join(IntegrationUtils.getFields('Book__c'), ', ');

        String fieldsCategory = String.join(
            IntegrationUtils.addRelationshipObjectToFields(IntegrationUtils.getFields('Category__c'), 'Category__r'), 
            ','
        );

        String filter = String.isNotEmpty(title) ? ' WHERE Name = :title' : ''; 
        filter = String.isNotEmpty(isbn13) ? (String.isNotEmpty(title) ? ' AND ISBN__c = :isbn13' : ' WHERE ISBN__c = :isbn13') : filter;
        filter = String.isNotEmpty(isbn10) ? (String.isNotEmpty(title) ? ' AND ISBN10__c = :isbn10' : ' WHERE ISBN10__c = :isbn10') : filter;

        String query = 'SELECT ' + fieldsBook + ', (SELECT ' + fieldsCategory + ' from BookCategories__r) ' +
                        ' FROM Book__c' + filter + ' ORDER BY Name';

        List<Book__c> bookList = Database.query(query);
        return bookList;

        // String jsonString = JSON.serialize(bookList);

        // System.debug((List<Object>) JSON.deserializeUntyped(jsonString));
        // List<Object> myObj = (List<Object>) JSON.deserializeUntyped(jsonString);
        // Map<String,Object> o = (Map<String,Object>) myObj[0];
        // system.debug((String) o.get('Name'));



        // return new ResponseModel(myObj);
    }

    global class ResponseModel {
        global List<Object> response;

        global ResponseModel(List<Object> data){
            this.response = data;
        }
    }

    global class Response {
        global List<String> response;

        global Response(){
        }
    }

    
}